name: GitHub Actions Demo
run-name: Run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi from CI"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install
        run: npm install
      # - name: Run tests
      #   run: npm run test:unit
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: 1.8.6
    - name: Add Azure integration
      run: packer plugins install github.com/hashicorp/azure
    - name: Build Azure image
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
      run: |
        cd devops && packer build \
        -var client_id=$CLIENT_ID \
        -var client_secret=$CLIENT_SECRET \
        -var tenant_id=$TENANT_ID \
        packer.json
